# Preprocessing

## Imports

In [2]:
import pandas as pd
import numpy as np
import random
import src.util.data.preprocessing.gtsdb_to_yolo as gtsdb_to_yolo
import src.util.data.preprocessing.train_test_split as tts
import importlib

importlib.reload(tts)
importlib.reload(gtsdb_to_yolo)

## Set Seed

In [2]:
random.seed(42)

## Load data

In [3]:
df = pd.read_csv('../data/raw/gt.txt', sep=';', header=None)

df.head()

           0    1    2     3    4   5
0  00000.ppm  774  411   815  446  11
1  00001.ppm  983  388  1024  432  40
2  00001.ppm  386  494   442  552  38
3  00001.ppm  973  335  1031  390  13
4  00002.ppm  892  476  1006  592  39

## GTSDB to YOLO format

In [4]:
images_dir = "../data/raw/"

df_yolo = gtsdb_to_yolo.gtsdb_to_yolo(df, images_dir)

In [5]:
df_yolo.head()

    filename  class_id  x_center  y_center     width   height
0  00000.ppm         0  0.584191  0.535625  0.030147  0.04375
1  00001.ppm         0  0.737868  0.512500  0.030147  0.05500
2  00001.ppm         0  0.304412  0.653750  0.041176  0.07250
3  00001.ppm         0  0.736765  0.453125  0.042647  0.06875
4  00002.ppm         0  0.697794  0.667500  0.083824  0.14500

In [6]:
df_yolo.describe()

       class_id     x_center     y_center        width       height
count    1213.0  1213.000000  1213.000000  1213.000000  1213.000000
mean        0.0     0.563178     0.564189     0.032058     0.053578
std         0.0     0.233189     0.110687     0.016060     0.026251
min         0.0     0.030882     0.069375     0.011765     0.020000
25%         0.0     0.371324     0.502500     0.020588     0.035000
50%         0.0     0.612500     0.565625     0.027941     0.046250
75%         0.0     0.736765     0.651875     0.038971     0.065000
max         0.0     0.972794     0.865625     0.093382     0.160000

## Train Test Split

In [7]:
grouped = df_yolo.groupby("filename")
image_files = list(grouped.groups.keys())

random.shuffle(image_files)

In [8]:
len(image_files)

741

In [9]:
train_files = image_files[:500]
val_files   = image_files[500:650]
test_files  = image_files[650:900]

In [13]:
images_src = "../data/raw"
base_out = "../data/processed"

tts.process_split(train_files, "train", grouped, images_src, base_out)
tts.process_split(val_files, "val", grouped, images_src, base_out)
tts.process_split(test_files, "test", grouped, images_src, base_out)

In [15]:
tts.check_dataset_integrity(base_out)

🔍 Checking split: train
Images: 500
Labels: 500
Image-label pairing OK
No empty labels
Label values valid

🔍 Checking split: val
Images: 150
Labels: 150
Image-label pairing OK
No empty labels
Label values valid

🔍 Checking split: test
Images: 91
Labels: 91
Image-label pairing OK
No empty labels
Label values valid

In [4]:
tts.convert_dataset_ppm_to_jpg("../data/processed/images")

Processing: ../data/processed/images\train
Converted: 00001.ppm → 00001.jpg
Converted: 00002.ppm → 00002.jpg
Converted: 00004.ppm → 00004.jpg
Converted: 00005.ppm → 00005.jpg
Converted: 00008.ppm → 00008.jpg
Converted: 00009.ppm → 00009.jpg
Converted: 00010.ppm → 00010.jpg
Converted: 00012.ppm → 00012.jpg
Converted: 00013.ppm → 00013.jpg
Converted: 00014.ppm → 00014.jpg
Converted: 00015.ppm → 00015.jpg
Converted: 00016.ppm → 00016.jpg
Converted: 00017.ppm → 00017.jpg
Converted: 00018.ppm → 00018.jpg
Converted: 00020.ppm → 00020.jpg
Converted: 00022.ppm → 00022.jpg
Converted: 00023.ppm → 00023.jpg
Converted: 00024.ppm → 00024.jpg
Converted: 00026.ppm → 00026.jpg
Converted: 00028.ppm → 00028.jpg
Converted: 00029.ppm → 00029.jpg
Converted: 00031.ppm → 00031.jpg
Converted: 00033.ppm → 00033.jpg
Converted: 00034.ppm → 00034.jpg
Converted: 00035.ppm → 00035.jpg
Converted: 00036.ppm → 00036.jpg
Converted: 00037.ppm → 00037.jpg
Converted: 00038.ppm → 00038.jpg
Converted: 00039.ppm → 00039.jpg
Converted: 00040.ppm → 00040.jpg
Converted: 00041.ppm → 00041.jpg
Converted: 00042.ppm → 00042.jpg
Converted: 00043.ppm → 00043.jpg
Converted: 00045.ppm → 00045.jpg
Converted: 00047.ppm → 00047.jpg
Converted: 00049.ppm → 00049.jpg
Converted: 00050.ppm → 00050.jpg
Converted: 00051.ppm → 00051.jpg
Converted: 00052.ppm → 00052.jpg
Converted: 00053.ppm → 00053.jpg
Converted: 00054.ppm → 00054.jpg
Converted: 00056.ppm → 00056.jpg
Converted: 00058.ppm → 00058.jpg
Converted: 00061.ppm → 00061.jpg
Converted: 00063.ppm → 00063.jpg
Converted: 00064.ppm → 00064.jpg
Converted: 00066.ppm → 00066.jpg
Converted: 00068.ppm → 00068.jpg
Converted: 00074.ppm → 00074.jpg
Converted: 00075.ppm → 00075.jpg
Converted: 00076.ppm → 00076.jpg
Converted: 00077.ppm → 00077.jpg
Converted: 00078.ppm → 00078.jpg
Converted: 00079.ppm → 00079.jpg
Converted: 00082.ppm → 00082.jpg
Converted: 00083.ppm → 00083.jpg
Converted: 00084.ppm → 00084.jpg
Converted: 00085.ppm → 00085.jpg
Converted: 00086.ppm → 00086.jpg
Converted: 00088.ppm → 00088.jpg
Converted: 00090.ppm → 00090.jpg
Converted: 00091.ppm → 00091.jpg
Converted: 00092.ppm → 00092.jpg
Converted: 00101.ppm → 00101.jpg
Converted: 00102.ppm → 00102.jpg
Converted: 00105.ppm → 00105.jpg
Converted: 00106.ppm → 00106.jpg
Converted: 00107.ppm → 00107.jpg
Converted: 00110.ppm → 00110.jpg
Converted: 00111.ppm → 00111.jpg
Converted: 00112.ppm → 00112.jpg
Converted: 00114.ppm → 00114.jpg
Converted: 00116.ppm → 00116.jpg
Converted: 00117.ppm → 00117.jpg
Converted: 00119.ppm → 00119.jpg
Converted: 00120.ppm → 00120.jpg
Converted: 00121.ppm → 00121.jpg
Converted: 00122.ppm → 00122.jpg
Converted: 00123.ppm → 00123.jpg
Converted: 00125.ppm → 00125.jpg
Converted: 00126.ppm → 00126.jpg
Converted: 00127.ppm → 00127.jpg
Converted: 00130.ppm → 00130.jpg
Converted: 00131.ppm → 00131.jpg
Converted: 00133.ppm → 00133.jpg
Converted: 00134.ppm → 00134.jpg
Converted: 00135.ppm → 00135.jpg
Converted: 00137.ppm → 00137.jpg
Converted: 00138.ppm → 00138.jpg
Converted: 00140.ppm → 00140.jpg
Converted: 00141.ppm → 00141.jpg
Converted: 00142.ppm → 00142.jpg
Converted: 00146.ppm → 00146.jpg
Converted: 00147.ppm → 00147.jpg
Converted: 00148.ppm → 00148.jpg
Converted: 00150.ppm → 00150.jpg
Converted: 00151.ppm → 00151.jpg
Converted: 00152.ppm → 00152.jpg
Converted: 00153.ppm → 00153.jpg
Converted: 00154.ppm → 00154.jpg
Converted: 00155.ppm → 00155.jpg
Converted: 00156.ppm → 00156.jpg
Converted: 00157.ppm → 00157.jpg
Converted: 00158.ppm → 00158.jpg
Converted: 00160.ppm → 00160.jpg
Converted: 00161.ppm → 00161.jpg
Converted: 00163.ppm → 00163.jpg
Converted: 00165.ppm → 00165.jpg
Converted: 00167.ppm → 00167.jpg
Converted: 00171.ppm → 00171.jpg
Converted: 00173.ppm → 00173.jpg
Converted: 00174.ppm → 00174.jpg
Converted: 00175.ppm → 00175.jpg
Converted: 00176.ppm → 00176.jpg
Converted: 00177.ppm → 00177.jpg
Converted: 00179.ppm → 00179.jpg
Converted: 00180.ppm → 00180.jpg
Converted: 00181.ppm → 00181.jpg
Converted: 00182.ppm → 00182.jpg
Converted: 00183.ppm → 00183.jpg
Converted: 00184.ppm → 00184.jpg
Converted: 00186.ppm → 00186.jpg
Converted: 00187.ppm → 00187.jpg
Converted: 00188.ppm → 00188.jpg
Converted: 00189.ppm → 00189.jpg
Converted: 00190.ppm → 00190.jpg
Converted: 00191.ppm → 00191.jpg
Converted: 00192.ppm → 00192.jpg
Converted: 00193.ppm → 00193.jpg
Converted: 00194.ppm → 00194.jpg
Converted: 00195.ppm → 00195.jpg
Converted: 00196.ppm → 00196.jpg
Converted: 00198.ppm → 00198.jpg
Converted: 00200.ppm → 00200.jpg
Converted: 00201.ppm → 00201.jpg
Converted: 00202.ppm → 00202.jpg
Converted: 00203.ppm → 00203.jpg
Converted: 00204.ppm → 00204.jpg
Converted: 00205.ppm → 00205.jpg
Converted: 00207.ppm → 00207.jpg
Converted: 00209.ppm → 00209.jpg
Converted: 00210.ppm → 00210.jpg
Converted: 00211.ppm → 00211.jpg
Converted: 00212.ppm → 00212.jpg
Converted: 00214.ppm → 00214.jpg
Converted: 00215.ppm → 00215.jpg
Converted: 00216.ppm → 00216.jpg
Converted: 00217.ppm → 00217.jpg
Converted: 00219.ppm → 00219.jpg
Converted: 00222.ppm → 00222.jpg
Converted: 00225.ppm → 00225.jpg
Converted: 00226.ppm → 00226.jpg
Converted: 00230.ppm → 00230.jpg
Converted: 00231.ppm → 00231.jpg
Converted: 00236.ppm → 00236.jpg
Converted: 00237.ppm → 00237.jpg
Converted: 00241.ppm → 00241.jpg
Converted: 00242.ppm → 00242.jpg
Converted: 00244.ppm → 00244.jpg
Converted: 00245.ppm → 00245.jpg
Converted: 00246.ppm → 00246.jpg
Converted: 00247.ppm → 00247.jpg
Converted: 00249.ppm → 00249.jpg
Converted: 00252.ppm → 00252.jpg
Converted: 00254.ppm → 00254.jpg
Converted: 00256.ppm → 00256.jpg
Converted: 00259.ppm → 00259.jpg
Converted: 00260.ppm → 00260.jpg
Converted: 00261.ppm → 00261.jpg
Converted: 00263.ppm → 00263.jpg
Converted: 00264.ppm → 00264.jpg
Converted: 00265.ppm → 00265.jpg
Converted: 00266.ppm → 00266.jpg
Converted: 00267.ppm → 00267.jpg
Converted: 00268.ppm → 00268.jpg
Converted: 00269.ppm → 00269.jpg
Converted: 00270.ppm → 00270.jpg
Converted: 00271.ppm → 00271.jpg
Converted: 00272.ppm → 00272.jpg
Converted: 00273.ppm → 00273.jpg
Converted: 00277.ppm → 00277.jpg
Converted: 00280.ppm → 00280.jpg
Converted: 00282.ppm → 00282.jpg
Converted: 00283.ppm → 00283.jpg
Converted: 00284.ppm → 00284.jpg
Converted: 00285.ppm → 00285.jpg
Converted: 00287.ppm → 00287.jpg
Converted: 00288.ppm → 00288.jpg
Converted: 00291.ppm → 00291.jpg
Converted: 00292.ppm → 00292.jpg
Converted: 00293.ppm → 00293.jpg
Converted: 00294.ppm → 00294.jpg
Converted: 00295.ppm → 00295.jpg
Converted: 00296.ppm → 00296.jpg
Converted: 00297.ppm → 00297.jpg
Converted: 00298.ppm → 00298.jpg
Converted: 00299.ppm → 00299.jpg
Converted: 00300.ppm → 00300.jpg
Converted: 00302.ppm → 00302.jpg
Converted: 00303.ppm → 00303.jpg
Converted: 00304.ppm → 00304.jpg
Converted: 00306.ppm → 00306.jpg
Converted: 00307.ppm → 00307.jpg
Converted: 00309.ppm → 00309.jpg
Converted: 00310.ppm → 00310.jpg
Converted: 00312.ppm → 00312.jpg
Converted: 00313.ppm → 00313.jpg
Converted: 00314.ppm → 00314.jpg
Converted: 00315.ppm → 00315.jpg
Converted: 00316.ppm → 00316.jpg
Converted: 00317.ppm → 00317.jpg
Converted: 00318.ppm → 00318.jpg
Converted: 00319.ppm → 00319.jpg
Converted: 00322.ppm → 00322.jpg
Converted: 00323.ppm → 00323.jpg
Converted: 00330.ppm → 00330.jpg
Converted: 00333.ppm → 00333.jpg
Converted: 00337.ppm → 00337.jpg
Converted: 00338.ppm → 00338.jpg
Converted: 00341.ppm → 00341.jpg
Converted: 00343.ppm → 00343.jpg
Converted: 00344.ppm → 00344.jpg
Converted: 00346.ppm → 00346.jpg
Converted: 00347.ppm → 00347.jpg
Converted: 00348.ppm → 00348.jpg
Converted: 00349.ppm → 00349.jpg
Converted: 00352.ppm → 00352.jpg
Converted: 00353.ppm → 00353.jpg
Converted: 00355.ppm → 00355.jpg
Converted: 00356.ppm → 00356.jpg
Converted: 00357.ppm → 00357.jpg
Converted: 00359.ppm → 00359.jpg
Converted: 00360.ppm → 00360.jpg
Converted: 00362.ppm → 00362.jpg
Converted: 00363.ppm → 00363.jpg
Converted: 00366.ppm → 00366.jpg
Converted: 00368.ppm → 00368.jpg
Converted: 00372.ppm → 00372.jpg
Converted: 00373.ppm → 00373.jpg
Converted: 00374.ppm → 00374.jpg
Converted: 00376.ppm → 00376.jpg
Converted: 00377.ppm → 00377.jpg
Converted: 00378.ppm → 00378.jpg
Converted: 00379.ppm → 00379.jpg
Converted: 00380.ppm → 00380.jpg
Converted: 00382.ppm → 00382.jpg
Converted: 00383.ppm → 00383.jpg
Converted: 00384.ppm → 00384.jpg
Converted: 00385.ppm → 00385.jpg
Converted: 00388.ppm → 00388.jpg
Converted: 00390.ppm → 00390.jpg
Converted: 00391.ppm → 00391.jpg
Converted: 00393.ppm → 00393.jpg
Converted: 00395.ppm → 00395.jpg
Converted: 00398.ppm → 00398.jpg
Converted: 00401.ppm → 00401.jpg
Converted: 00402.ppm → 00402.jpg
Converted: 00403.ppm → 00403.jpg
Converted: 00404.ppm → 00404.jpg
Converted: 00405.ppm → 00405.jpg
Converted: 00408.ppm → 00408.jpg
Converted: 00410.ppm → 00410.jpg
Converted: 00412.ppm → 00412.jpg
Converted: 00413.ppm → 00413.jpg
Converted: 00414.ppm → 00414.jpg
Converted: 00415.ppm → 00415.jpg
Converted: 00420.ppm → 00420.jpg
Converted: 00421.ppm → 00421.jpg
Converted: 00422.ppm → 00422.jpg
Converted: 00425.ppm → 00425.jpg
Converted: 00426.ppm → 00426.jpg
Converted: 00427.ppm → 00427.jpg
Converted: 00428.ppm → 00428.jpg
Converted: 00430.ppm → 00430.jpg
Converted: 00431.ppm → 00431.jpg
Converted: 00432.ppm → 00432.jpg
Converted: 00433.ppm → 00433.jpg
Converted: 00434.ppm → 00434.jpg
Converted: 00435.ppm → 00435.jpg
Converted: 00438.ppm → 00438.jpg
Converted: 00439.ppm → 00439.jpg
Converted: 00444.ppm → 00444.jpg
Converted: 00446.ppm → 00446.jpg
Converted: 00447.ppm → 00447.jpg
Converted: 00448.ppm → 00448.jpg
Converted: 00450.ppm → 00450.jpg
Converted: 00451.ppm → 00451.jpg
Converted: 00452.ppm → 00452.jpg
Converted: 00455.ppm → 00455.jpg
Converted: 00456.ppm → 00456.jpg
Converted: 00457.ppm → 00457.jpg
Converted: 00458.ppm → 00458.jpg
Converted: 00459.ppm → 00459.jpg
Converted: 00460.ppm → 00460.jpg
Converted: 00461.ppm → 00461.jpg
Converted: 00463.ppm → 00463.jpg
Converted: 00466.ppm → 00466.jpg
Converted: 00467.ppm → 00467.jpg
Converted: 00471.ppm → 00471.jpg
Converted: 00472.ppm → 00472.jpg
Converted: 00473.ppm → 00473.jpg
Converted: 00474.ppm → 00474.jpg
Converted: 00476.ppm → 00476.jpg
Converted: 00477.ppm → 00477.jpg
Converted: 00479.ppm → 00479.jpg
Converted: 00480.ppm → 00480.jpg
Converted: 00481.ppm → 00481.jpg
Converted: 00483.ppm → 00483.jpg
Converted: 00484.ppm → 00484.jpg
Converted: 00486.ppm → 00486.jpg
Converted: 00487.ppm → 00487.jpg
Converted: 00488.ppm → 00488.jpg
Converted: 00490.ppm → 00490.jpg
Converted: 00491.ppm → 00491.jpg
Converted: 00492.ppm → 00492.jpg
Converted: 00493.ppm → 00493.jpg
Converted: 00494.ppm → 00494.jpg
Converted: 00496.ppm → 00496.jpg
Converted: 00497.ppm → 00497.jpg
Converted: 00499.ppm → 00499.jpg
Converted: 00500.ppm → 00500.jpg
Converted: 00502.ppm → 00502.jpg
Converted: 00504.ppm → 00504.jpg
Converted: 00505.ppm → 00505.jpg
Converted: 00507.ppm → 00507.jpg
Converted: 00508.ppm → 00508.jpg
Converted: 00513.ppm → 00513.jpg
Converted: 00514.ppm → 00514.jpg
Converted: 00516.ppm → 00516.jpg
Converted: 00517.ppm → 00517.jpg
Converted: 00518.ppm → 00518.jpg
Converted: 00519.ppm → 00519.jpg
Converted: 00523.ppm → 00523.jpg
Converted: 00524.ppm → 00524.jpg
Converted: 00527.ppm → 00527.jpg
Converted: 00528.ppm → 00528.jpg
Converted: 00531.ppm → 00531.jpg
Converted: 00542.ppm → 00542.jpg
Converted: 00544.ppm → 00544.jpg
Converted: 00545.ppm → 00545.jpg
Converted: 00548.ppm → 00548.jpg
Converted: 00551.ppm → 00551.jpg
Converted: 00552.ppm → 00552.jpg
Converted: 00554.ppm → 00554.jpg
Converted: 00556.ppm → 00556.jpg
Converted: 00557.ppm → 00557.jpg
Converted: 00560.ppm → 00560.jpg
Converted: 00565.ppm → 00565.jpg
Converted: 00566.ppm → 00566.jpg
Converted: 00570.ppm → 00570.jpg
Converted: 00571.ppm → 00571.jpg
Converted: 00575.ppm → 00575.jpg
Converted: 00593.ppm → 00593.jpg
Converted: 00601.ppm → 00601.jpg
Converted: 00602.ppm → 00602.jpg
Converted: 00603.ppm → 00603.jpg
Converted: 00604.ppm → 00604.jpg
Converted: 00605.ppm → 00605.jpg
Converted: 00608.ppm → 00608.jpg
Converted: 00609.ppm → 00609.jpg
Converted: 00611.ppm → 00611.jpg
Converted: 00613.ppm → 00613.jpg
Converted: 00620.ppm → 00620.jpg
Converted: 00621.ppm → 00621.jpg
Converted: 00622.ppm → 00622.jpg
Converted: 00623.ppm → 00623.jpg
Converted: 00626.ppm → 00626.jpg
Converted: 00630.ppm → 00630.jpg
Converted: 00631.ppm → 00631.jpg
Converted: 00632.ppm → 00632.jpg
Converted: 00633.ppm → 00633.jpg
Converted: 00634.ppm → 00634.jpg
Converted: 00635.ppm → 00635.jpg
Converted: 00637.ppm → 00637.jpg
Converted: 00638.ppm → 00638.jpg
Converted: 00639.ppm → 00639.jpg
Converted: 00640.ppm → 00640.jpg
Converted: 00644.ppm → 00644.jpg
Converted: 00646.ppm → 00646.jpg
Converted: 00649.ppm → 00649.jpg
Converted: 00650.ppm → 00650.jpg
Converted: 00653.ppm → 00653.jpg
Converted: 00656.ppm → 00656.jpg
Converted: 00657.ppm → 00657.jpg
Converted: 00658.ppm → 00658.jpg
Converted: 00659.ppm → 00659.jpg
Converted: 00660.ppm → 00660.jpg
Converted: 00664.ppm → 00664.jpg
Converted: 00667.ppm → 00667.jpg
Converted: 00668.ppm → 00668.jpg
Converted: 00671.ppm → 00671.jpg
Converted: 00672.ppm → 00672.jpg
Converted: 00675.ppm → 00675.jpg
Converted: 00678.ppm → 00678.jpg
Converted: 00679.ppm → 00679.jpg
Converted: 00681.ppm → 00681.jpg
Converted: 00682.ppm → 00682.jpg
Converted: 00683.ppm → 00683.jpg
Converted: 00685.ppm → 00685.jpg
Converted: 00686.ppm → 00686.jpg
Converted: 00689.ppm → 00689.jpg
Converted: 00690.ppm → 00690.jpg
Converted: 00692.ppm → 00692.jpg
Converted: 00694.ppm → 00694.jpg
Converted: 00695.ppm → 00695.jpg
Converted: 00696.ppm → 00696.jpg
Converted: 00697.ppm → 00697.jpg
Converted: 00698.ppm → 00698.jpg
Converted: 00700.ppm → 00700.jpg
Converted: 00701.ppm → 00701.jpg
Converted: 00702.ppm → 00702.jpg
Converted: 00703.ppm → 00703.jpg
Converted: 00704.ppm → 00704.jpg
Converted: 00707.ppm → 00707.jpg
Converted: 00712.ppm → 00712.jpg
Converted: 00714.ppm → 00714.jpg
Converted: 00717.ppm → 00717.jpg
Converted: 00719.ppm → 00719.jpg
Converted: 00720.ppm → 00720.jpg
Converted: 00721.ppm → 00721.jpg
Converted: 00722.ppm → 00722.jpg
Converted: 00725.ppm → 00725.jpg
Converted: 00729.ppm → 00729.jpg
Converted: 00730.ppm → 00730.jpg
Converted: 00732.ppm → 00732.jpg
Converted: 00734.ppm → 00734.jpg
Converted: 00738.ppm → 00738.jpg
Converted: 00740.ppm → 00740.jpg
Converted: 00741.ppm → 00741.jpg
Converted: 00744.ppm → 00744.jpg
Converted: 00747.ppm → 00747.jpg
Converted: 00749.ppm → 00749.jpg
Converted: 00751.ppm → 00751.jpg
Converted: 00754.ppm → 00754.jpg
Converted: 00755.ppm → 00755.jpg
Converted: 00756.ppm → 00756.jpg
Converted: 00761.ppm → 00761.jpg
Converted: 00762.ppm → 00762.jpg
Converted: 00763.ppm → 00763.jpg
Converted: 00764.ppm → 00764.jpg
Converted: 00766.ppm → 00766.jpg
Converted: 00770.ppm → 00770.jpg
Converted: 00771.ppm → 00771.jpg
Converted: 00775.ppm → 00775.jpg
Converted: 00776.ppm → 00776.jpg
Converted: 00779.ppm → 00779.jpg
Converted: 00783.ppm → 00783.jpg
Converted: 00784.ppm → 00784.jpg
Converted: 00787.ppm → 00787.jpg
Converted: 00788.ppm → 00788.jpg
Converted: 00789.ppm → 00789.jpg
Converted: 00791.ppm → 00791.jpg
Converted: 00794.ppm → 00794.jpg
Converted: 00795.ppm → 00795.jpg
Converted: 00797.ppm → 00797.jpg
Converted: 00798.ppm → 00798.jpg
Converted: 00805.ppm → 00805.jpg
Converted: 00806.ppm → 00806.jpg
Converted: 00807.ppm → 00807.jpg
Converted: 00808.ppm → 00808.jpg
Converted: 00811.ppm → 00811.jpg
Converted: 00813.ppm → 00813.jpg
Converted: 00816.ppm → 00816.jpg
Converted: 00817.ppm → 00817.jpg
Converted: 00818.ppm → 00818.jpg
Converted: 00821.ppm → 00821.jpg
Converted: 00822.ppm → 00822.jpg
Converted: 00823.ppm → 00823.jpg
Converted: 00825.ppm → 00825.jpg
Converted: 00829.ppm → 00829.jpg
Converted: 00831.ppm → 00831.jpg
Converted: 00834.ppm → 00834.jpg
Converted: 00836.ppm → 00836.jpg
Converted: 00839.ppm → 00839.jpg
Converted: 00841.ppm → 00841.jpg
Converted: 00842.ppm → 00842.jpg
Converted: 00844.ppm → 00844.jpg
Converted: 00845.ppm → 00845.jpg
Converted: 00846.ppm → 00846.jpg
Converted: 00850.ppm → 00850.jpg
Converted: 00851.ppm → 00851.jpg
Converted: 00852.ppm → 00852.jpg
Converted: 00853.ppm → 00853.jpg
Converted: 00854.ppm → 00854.jpg
Converted: 00860.ppm → 00860.jpg
Converted: 00863.ppm → 00863.jpg
Converted: 00864.ppm → 00864.jpg
Converted: 00866.ppm → 00866.jpg
Converted: 00868.ppm → 00868.jpg
Converted: 00871.ppm → 00871.jpg
Converted: 00874.ppm → 00874.jpg
Converted: 00879.ppm → 00879.jpg
Converted: 00881.ppm → 00881.jpg
Converted: 00882.ppm → 00882.jpg
Converted: 00886.ppm → 00886.jpg
Converted: 00887.ppm → 00887.jpg
Converted: 00894.ppm → 00894.jpg
Converted: 00896.ppm → 00896.jpg
Converted: 00897.ppm → 00897.jpg
Converted: 00899.ppm → 00899.jpg

Processing: ../data/processed/images\val
Converted: 00000.ppm → 00000.jpg
Converted: 00003.ppm → 00003.jpg
Converted: 00007.ppm → 00007.jpg
Converted: 00011.ppm → 00011.jpg
Converted: 00019.ppm → 00019.jpg
Converted: 00021.ppm → 00021.jpg
Converted: 00048.ppm → 00048.jpg
Converted: 00055.ppm → 00055.jpg
Converted: 00057.ppm → 00057.jpg
Converted: 00059.ppm → 00059.jpg
Converted: 00060.ppm → 00060.jpg
Converted: 00062.ppm → 00062.jpg
Converted: 00065.ppm → 00065.jpg
Converted: 00067.ppm → 00067.jpg
Converted: 00069.ppm → 00069.jpg
Converted: 00070.ppm → 00070.jpg
Converted: 00072.ppm → 00072.jpg
Converted: 00087.ppm → 00087.jpg
Converted: 00093.ppm → 00093.jpg
Converted: 00096.ppm → 00096.jpg
Converted: 00097.ppm → 00097.jpg
Converted: 00098.ppm → 00098.jpg
Converted: 00100.ppm → 00100.jpg
Converted: 00109.ppm → 00109.jpg
Converted: 00113.ppm → 00113.jpg
Converted: 00118.ppm → 00118.jpg
Converted: 00124.ppm → 00124.jpg
Converted: 00129.ppm → 00129.jpg
Converted: 00132.ppm → 00132.jpg
Converted: 00136.ppm → 00136.jpg
Converted: 00143.ppm → 00143.jpg
Converted: 00149.ppm → 00149.jpg
Converted: 00159.ppm → 00159.jpg
Converted: 00164.ppm → 00164.jpg
Converted: 00168.ppm → 00168.jpg
Converted: 00172.ppm → 00172.jpg
Converted: 00185.ppm → 00185.jpg
Converted: 00197.ppm → 00197.jpg
Converted: 00208.ppm → 00208.jpg
Converted: 00220.ppm → 00220.jpg
Converted: 00221.ppm → 00221.jpg
Converted: 00223.ppm → 00223.jpg
Converted: 00233.ppm → 00233.jpg
Converted: 00234.ppm → 00234.jpg
Converted: 00239.ppm → 00239.jpg
Converted: 00240.ppm → 00240.jpg
Converted: 00248.ppm → 00248.jpg
Converted: 00250.ppm → 00250.jpg
Converted: 00251.ppm → 00251.jpg
Converted: 00253.ppm → 00253.jpg
Converted: 00257.ppm → 00257.jpg
Converted: 00258.ppm → 00258.jpg
Converted: 00262.ppm → 00262.jpg
Converted: 00274.ppm → 00274.jpg
Converted: 00276.ppm → 00276.jpg
Converted: 00279.ppm → 00279.jpg
Converted: 00290.ppm → 00290.jpg
Converted: 00311.ppm → 00311.jpg
Converted: 00320.ppm → 00320.jpg
Converted: 00334.ppm → 00334.jpg
Converted: 00339.ppm → 00339.jpg
Converted: 00340.ppm → 00340.jpg
Converted: 00350.ppm → 00350.jpg
Converted: 00358.ppm → 00358.jpg
Converted: 00369.ppm → 00369.jpg
Converted: 00370.ppm → 00370.jpg
Converted: 00386.ppm → 00386.jpg
Converted: 00397.ppm → 00397.jpg
Converted: 00411.ppm → 00411.jpg
Converted: 00419.ppm → 00419.jpg
Converted: 00423.ppm → 00423.jpg
Converted: 00436.ppm → 00436.jpg
Converted: 00440.ppm → 00440.jpg
Converted: 00441.ppm → 00441.jpg
Converted: 00443.ppm → 00443.jpg
Converted: 00445.ppm → 00445.jpg
Converted: 00449.ppm → 00449.jpg
Converted: 00453.ppm → 00453.jpg
Converted: 00470.ppm → 00470.jpg
Converted: 00475.ppm → 00475.jpg
Converted: 00478.ppm → 00478.jpg
Converted: 00482.ppm → 00482.jpg
Converted: 00485.ppm → 00485.jpg
Converted: 00501.ppm → 00501.jpg
Converted: 00509.ppm → 00509.jpg
Converted: 00520.ppm → 00520.jpg
Converted: 00521.ppm → 00521.jpg
Converted: 00530.ppm → 00530.jpg
Converted: 00536.ppm → 00536.jpg
Converted: 00564.ppm → 00564.jpg
Converted: 00567.ppm → 00567.jpg
Converted: 00599.ppm → 00599.jpg
Converted: 00606.ppm → 00606.jpg
Converted: 00607.ppm → 00607.jpg
Converted: 00610.ppm → 00610.jpg
Converted: 00615.ppm → 00615.jpg
Converted: 00616.ppm → 00616.jpg
Converted: 00619.ppm → 00619.jpg
Converted: 00624.ppm → 00624.jpg
Converted: 00625.ppm → 00625.jpg
Converted: 00628.ppm → 00628.jpg
Converted: 00641.ppm → 00641.jpg
Converted: 00642.ppm → 00642.jpg