# Preprocessing

## Imports

In [17]:
import pandas as pd
import numpy as np
import random
import src.util.data.preprocessing.gtsdb_to_yolo as gtsdb_to_yolo
import src.util.data.preprocessing.train_test_split as tts
import importlib

importlib.reload(tts)
importlib.reload(gtsdb_to_yolo)

## Set Seed

In [9]:
random.seed(42)

## Load data

In [2]:
df = pd.read_csv('../data/raw/gt.txt', sep=';', header=None)

df.head()

           0    1    2     3    4   5
0  00000.ppm  774  411   815  446  11
1  00001.ppm  983  388  1024  432  40
2  00001.ppm  386  494   442  552  38
3  00001.ppm  973  335  1031  390  13
4  00002.ppm  892  476  1006  592  39

## GTSDB to YOLO format

In [3]:
images_dir = "../data/raw/"

df_yolo = gtsdb_to_yolo.gtsdb_to_yolo(df, images_dir)

In [4]:
df_yolo.head()

    filename  class_id  x_center  y_center     width   height
0  00000.ppm         0  0.584191  0.535625  0.030147  0.04375
1  00001.ppm         0  0.737868  0.512500  0.030147  0.05500
2  00001.ppm         0  0.304412  0.653750  0.041176  0.07250
3  00001.ppm         0  0.736765  0.453125  0.042647  0.06875
4  00002.ppm         0  0.697794  0.667500  0.083824  0.14500

In [5]:
df_yolo.describe()

       class_id     x_center     y_center        width       height
count    1213.0  1213.000000  1213.000000  1213.000000  1213.000000
mean        0.0     0.563178     0.564189     0.032058     0.053578
std         0.0     0.233189     0.110687     0.016060     0.026251
min         0.0     0.030882     0.069375     0.011765     0.020000
25%         0.0     0.371324     0.502500     0.020588     0.035000
50%         0.0     0.612500     0.565625     0.027941     0.046250
75%         0.0     0.736765     0.651875     0.038971     0.065000
max         0.0     0.972794     0.865625     0.093382     0.160000

## Train Test Split

In [10]:
grouped = df_yolo.groupby("filename")
image_files = list(grouped.groups.keys())

random.shuffle(image_files)

In [20]:
len(image_files)

741

In [11]:
train_files = image_files[:600]
val_files   = image_files[600:800]
test_files  = image_files[800:900]

In [19]:
test_files

[]

In [18]:
images_src = "../data/raw"
base_out = "../data/processed"

tts.process_split(train_files, "train", grouped, images_src, base_out)
tts.process_split(val_files, "val", grouped, images_src, base_out)
tts.process_split(test_files, "test", grouped, images_src, base_out)